### ISSUE TITLE
Consider editable domain list for include

### ISSUE THREAD

**Issue by coinzdude** [coinzdude/javascript-errors-notifier#1]
Consider extending configuration options for per domain extension activation, so with "all domains" disabled, would allow a list of included domains to be enabled for the extension.  Possibly with regex support.
e.g.

mydomain.com
someotherdomain.com

**Comment by coinzdude** [comment]
Basic support is available to specify a list of domains to activate the extension. To use, disable "Show error notification icon on all domains" and then specify one or more line separated domains.

![image](https://user-images.githubusercontent.com/58857646/224592972-21f51072-17d0-43d2-8656-624f3e019d5c.png)

**Comment by jeroen** [comment]
Does this include subdomains? My site has many subdomains, I would like to enable it on *.mydomain.com

**Comment by coinzdude** [comment]
Yes, this is the way it works currently. If you use domain.com, it will activate on all subdomains.

**Comment by coinzdude** [comment]
Just committed a fix to clarify this in the UI, waiting on chrome store for update window
